import { Question } from '@/types'

export const QUESTIONS: Question[] = [
  {
    id: 'color',
    type: 'color-picker',
    order: 1,
    title: '색',
    subtitle: 'Color',
    description: '이 멤버를 떠올리면 어떤 색이 보이나요?',
    options: [
      { value: '#FFD700', label: '황금빛' },
      { value: '#FF6B6B', label: '산호빛' },
      { value: '#4ECDC4', label: '청록빛' },
      { value: '#9B59B6', label: '보라빛' },
      { value: '#2C3E50', label: '심해빛' },
      { value: '#F39C12', label: '호박빛' },
      { value: '#1ABC9C', label: '에메랄드' },
      { value: '#E74C3C', label: '루비빛' },
      { value: '#ECF0F1', label: '은빛' },
      { value: '#34495E', label: '먹빛' },
      { value: '#FF9FF3', label: '핑크빛' },
      { value: '#00D2D3', label: '하늘빛' },
    ],
    allowCustom: true,
  },
  {
    id: 'season',
    type: 'single-select',
    order: 2,
    title: '계절',
    subtitle: 'Season',
    description: '이 멤버는 어떤 계절의 분위기인가요?',
    options: [
      { value: 'spring', label: '봄', emoji: '🌸', description: '새로운 시작과 생명', imageSrc: '/images/options/season/spring.png' },
      { value: 'summer', label: '여름', emoji: '☀️', description: '열정과 활력', imageSrc: '/images/options/season/summer.png' },
      { value: 'autumn', label: '가을', emoji: '🍂', description: '성숙과 풍요', imageSrc: '/images/options/season/autumn.png' },
      { value: 'winter', label: '겨울', emoji: '❄️', description: '고요와 신비', imageSrc: '/images/options/season/winter.png' },
    ],
  },
  {
    id: 'timeOfDay',
    type: 'single-select',
    order: 3,
    title: '시간대',
    subtitle: 'Time of Day',
    description: '이 멤버를 만난다면 언제일 것 같나요?',
    options: [
      { value: 'dawn', label: '새벽', description: '4AM - 7AM', imageSrc: '/images/options/time-of-day/dawn.png' },
      { value: 'morning', label: '아침', description: '7AM - 12PM', imageSrc: '/images/options/time-of-day/morning.png' },
      { value: 'afternoon', label: '오후', description: '12PM - 6PM', imageSrc: '/images/options/time-of-day/afternoon.png' },
      { value: 'night', label: '밤', description: '6PM - 4AM', imageSrc: '/images/options/time-of-day/night.png' },
    ],
  },
  {
    id: 'texture',
    type: 'single-select',
    order: 4,
    title: '질감',
    subtitle: 'Texture',
    description: '이 멤버를 만진다면 어떤 느낌일까요?',
    options: [
      { value: 'soft', label: '부드러운', description: '솜처럼 포근한', imageSrc: '/images/options/texture/soft.png' },
      { value: 'rough', label: '거친', description: '바위처럼 단단한', imageSrc: '/images/options/texture/rough.png' },
      { value: 'flowing', label: '흐르는', description: '물처럼 유연한', imageSrc: '/images/options/texture/flowing.png' },
      { value: 'sharp', label: '날카로운', description: '유리처럼 선명한', imageSrc: '/images/options/texture/sharp.png' },
      { value: 'warm', label: '따뜻한', description: '햇살처럼 온화한', imageSrc: '/images/options/texture/warm.png' },
      { value: 'cool', label: '차가운', description: '대리석처럼 시원한', imageSrc: '/images/options/texture/cool.png' },
    ],
  },
  {
    id: 'emotion',
    type: 'single-select',
    order: 5,
    title: '감정',
    subtitle: 'Emotion',
    description: '이 멤버가 불러일으키는 감정은?',
    options: [
      { value: 'warm', label: '따뜻한', description: '마음이 녹는 듯한', imageSrc: '/images/options/emotion/warm.png' },
      { value: 'cold', label: '차가운', description: '서늘하고 고고한', imageSrc: '/images/options/emotion/cold.png' },
      { value: 'intense', label: '강렬한', description: '눈을 뗄 수 없는', imageSrc: '/images/options/emotion/intense.png' },
      { value: 'peaceful', label: '평온한', description: '마음이 편안한', imageSrc: '/images/options/emotion/peaceful.png' },
      { value: 'mysterious', label: '신비로운', description: '알 수 없는 깊이', imageSrc: '/images/options/emotion/mysterious.png' },
      { value: 'playful', label: '장난스러운', description: '웃음이 나는', imageSrc: '/images/options/emotion/playful.png' },
    ],
  },
  {
    id: 'oneWord',
    type: 'text-input',
    order: 6,
    title: '한 단어',
    subtitle: 'One Word',
    description: '이 멤버를 정의하는 단 하나의 단어는?',
    placeholder: '자유롭게 입력해주세요',
    maxLength: 20,
  },
]

export const getQuestionById = (id: string): Question | undefined =>
  QUESTIONS.find((q) => q.id === id)
